" Name:         Edge
" Description:  Clean & Elegant Color Scheme inspired by Atom One and Material
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/edge/
" License:      MIT && Anti-996
" Last Updated: Fri 06 Dec 2019 08:05:53 AM CST

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'edge'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

hi! link plug2 Cyan
hi! link plugBracket Blue
hi! link plugName Green
hi! link plugDash Blue
hi! link plugNotLoaded Grey
hi! link plugH2 Blue
hi! link plugMessage Blue
hi! link plugError Red
hi! link plugRelDate Grey
hi! link plugStar Purple
hi! link plugUpdate Cyan
hi! link plugDeleted Grey
hi! link plugEdge Purple
hi! link EasyMotionTarget Search
hi! link EasyMotionShade Grey
hi! link Sneak Search
hi! link SneakLabel Search
hi! link gitcommitSelectedFile Green
hi! link gitcommitDiscardedFile Red
let g:fzf_colors = {
      \ 'fg':      ['fg', 'Normal'],
      \ 'bg':      ['bg', 'Normal'],
      \ 'hl':      ['fg', 'Green'],
      \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
      \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
      \ 'hl+':     ['fg', 'Green'],
      \ 'info':    ['fg', 'Cyan'],
      \ 'prompt':  ['fg', 'Purple'],
      \ 'pointer': ['fg', 'Blue'],
      \ 'marker':  ['fg', 'Blue'],
      \ 'spinner': ['fg', 'Yellow'],
      \ 'header':  ['fg', 'Blue']
      \ }
if !exists('g:Lf_StlColorscheme')
  let g:Lf_StlColorscheme = 'one'
endif
hi! link StartifyBracket Grey
hi! link StartifyFile Fg
hi! link StartifyNumber Red
hi! link StartifyPath Green
hi! link StartifySlash Cyan
hi! link StartifySection Blue
hi! link StartifyHeader Purple
hi! link StartifySpecial Grey
hi! link netrwDir Green
hi! link netrwClassify Green
hi! link netrwLink Grey
hi! link netrwSymLink Fg
hi! link netrwExe Red
hi! link netrwComment Grey
hi! link netrwList Cyan
hi! link netrwHelpCmd Blue
hi! link netrwCmdSep Grey
hi! link netrwVersion Purple
hi! link NERDTreeDir Green
hi! link NERDTreeDirSlash Cyan
hi! link NERDTreeOpenable Blue
hi! link NERDTreeClosable Blue
hi! link NERDTreeFile Fg
hi! link NERDTreeExecFile Red
hi! link NERDTreeUp Grey
hi! link NERDTreeCWD Purple
hi! link NERDTreeHelp Grey
hi! link NERDTreeToggleOn Green
hi! link NERDTreeToggleOff Red
hi! link NERDTreeFlags Blue
hi! link NERDTreeLinkFile Grey
hi! link NERDTreeLinkTarget Green
hi! link TagbarFoldIcon Blue
hi! link TagbarSignature Green
hi! link TagbarKind Purple
hi! link TagbarScope Red
hi! link TagbarNestedKind Blue
hi! link TagbarVisibilityPrivate Red
hi! link TagbarVisibilityPublic Blue
hi! link ALEVirtualTextError Grey
hi! link ALEVirtualTextWarning Grey
hi! link ALEVirtualTextInfo Grey
hi! link ALEVirtualTextStyleError ALEVirtualTextError
hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
hi! link CocCodeLens Grey
hi! link CocErrorSign ALEErrorSign
hi! link CocWarningSign ALEWarningSign
hi! link CocInfoSign ALEInfoSign
hi! link CocHintSign Label
hi! link CocErrorHighlight ALEError
hi! link CocWarningHighlight ALEWarning
hi! link CocInfoHighlight ALEInfo
hi! link CocWarningVirtualText ALEVirtualTextWarning
hi! link CocErrorVirtualText ALEVirtualTextError
hi! link CocInfoVirtualText ALEVirtualTextInfo
hi! link CocHintVirtualText ALEVirtualTextInfo
hi! link CocGitAddedSign GitGutterAdd
hi! link CocGitChangeRemovedSign GitGutterChangeDelete
hi! link CocGitChangedSign GitGutterChange
hi! link CocGitRemovedSign GitGutterDelete
hi! link CocGitTopRemovedSign GitGutterDelete
hi! link CocExplorerBufferRoot Purple
hi! link CocExplorerBufferExpandIcon Red
hi! link CocExplorerBufferBufnr Yellow
hi! link CocExplorerBufferModified Red
hi! link CocExplorerBufferBufname Grey
hi! link CocExplorerFileRoot Purple
hi! link CocExplorerFileExpandIcon Red
hi! link CocExplorerFileFullpath Cyan
hi! link CocExplorerFileDirectory Green
hi! link CocExplorerFileGitStage Blue
hi! link CocExplorerFileGitUnstage Yellow
hi! link CocExplorerFileSize Blue
hi! link CocExplorerTimeAccessed Cyan
hi! link CocExplorerTimeCreated Cyan
hi! link CocExplorerTimeModified Cyan
hi! link UndotreeNode Blue
hi! link UndotreeNodeCurrent Purple
hi! link UndotreeSeq Green
hi! link UndotreeCurrent Cyan
hi! link UndotreeNext Yellow
hi! link UndotreeTimeStamp Grey
hi! link UndotreeHead Purple
hi! link UndotreeBranch Cyan
hi! link UndotreeSavedSmall Red
hi! link QuickmenuOption Green
hi! link QuickmenuNumber Red
hi! link QuickmenuBracket Grey
hi! link QuickmenuHelp Blue
hi! link QuickmenuSpecial Grey
hi! link QuickmenuHeader Purple
hi! link markdownLinkText Blue
hi! link markdownHeadingDelimiter Red
hi! link markdownIdDeclaration Cyan
hi! link markdownId Cyan
hi! link markdownListMarker Cyan
hi! link markdownCodeDelimiter Cyan
hi! link markdownCode Green
hi! link markdownBoldDelimiter Grey
hi! link markdownRule Purple
hi! link mkdLink Blue
hi! link mkdHeading Red
hi! link mkdLinkDef Cyan
hi! link mkdID Cyan
hi! link mkdListItem Cyan
hi! link mkdCodeDelimiter Cyan
hi! link mkdCode Green
hi! link mkdBold Grey
hi! link mkdRule Purple
hi! link rstDirective Blue
hi! link rstExplicitMarkup Red
hi! link rstInterpretedTextOrHyperlinkReference Green
hi! link rstInlineLiteral Green
hi! link rstSubstitutionReference Cyan
hi! link texStatement Blue
hi! link texDefCmd Red
hi! link texDefName Cyan
hi! link texOnlyMath Grey
hi! link htmlTag Purple
hi! link htmlArg Blue
hi! link htmlEndTag Blue
hi! link xmlTag Purple
hi! link xmlTagName Purple
hi! link xmlAttrib Blue
hi! link cssFunctionName Yellow
hi! link cssClassName Purple
hi! link cssClassNameDot Purple
hi! link cssAttrComma Fg
hi! link cssTagName Purple
hi! link cssBraces Fg
hi! link cssSelectorOp Fg
hi! link cssVendor Grey
hi! link cssSelectorOp2 Blue
hi! link cssImportant Red
hi! link sassMixing Green
hi! link sassClass Purple
hi! link sassClassChar Purple
hi! link sassMixin Blue
hi! link sassAmpersand Cyan
hi! link sassFunction Yellow
hi! link scssSelectorChar Purple
hi! link scssSelectorName Purple
hi! link scssForKeyword Red
hi! link scssDefault Red
hi! link scssAmpersand Cyan
hi! link scssMixinName Yellow
hi! link scssFunctionName Yellow
hi! link lessMixinChar Purple
hi! link lessClass Purple
hi! link lessVariable Red
hi! link lessAmpersandChar Cyan
hi! link lessFunction Yellow
hi! link jsGlobalNodeObjects Red
hi! link jsGlobalObjects Yellow
hi! link jsFunction Blue
hi! link jsObjectMethodType Red
hi! link jsOperatorKeyword Red
hi! link jsThis Cyan
hi! link jsParensError Red
hi! link jsArrowFunction Blue
hi! link jsTaggedTemplate Cyan
hi! link javaScriptReserved Purple
hi! link javaScriptBraces Fg
hi! link javaScriptOperator Red
hi! link javaScriptNull Yellow
hi! link javaScriptMessage Cyan
hi! link javaScriptGlobal Blue
hi! link typescriptLabel Purple
hi! link typescriptExceptions Red
hi! link typescriptBraces Fg
hi! link typescriptEndColons Fg
hi! link typescriptParens Fg
hi! link typescriptDocTags Purple
hi! link typescriptLogicSymbols Blue
hi! link typescriptImport Red
hi! link typescriptBOM Blue
hi! link typescriptVariableDeclaration Cyan
hi! link typescriptVariable Red
hi! link typescriptExport Purple
hi! link typescriptAliasDeclaration Yellow
hi! link typescriptClassName Blue
hi! link typescriptAccessibilityModifier Purple
hi! link typescriptOperator Red
hi! link typescriptArrowFunc Blue
hi! link typescriptMethodAccessor Red
hi! link typescriptMember Blue
hi! link typescriptTypeReference Cyan
hi! link typescriptDefault Yellow
hi! link typescriptTemplateSB Cyan
hi! link typescriptArrowFuncArg Cyan
hi! link typescriptParamImpl Green
hi! link typescriptFuncComma White
hi! link jsxOpenPunct Blue
hi! link typescriptCastKeyword Red
hi! link typescriptCall Blue
hi! link typescriptCase Red
hi! link dartMetadata Red
hi! link dartInterpolation Cyan
hi! link dartCoreClasses Blue
hi! link coffeeParens Green
hi! link coffeeCurly Fg
hi! link coffeeParen Fg
hi! link coffeeSpecialOp Fg
hi! link coffeeInterp Cyan
hi! link coffeeInterpDelim Cyan
hi! link coffeeConstant Blue
hi! link coffeeOperator Red
hi! link coffeeExtendedOp Blue
hi! link purescriptModuleKeyword Purple
hi! link purescriptModule Red
hi! link purescriptModuleName Red
hi! link purescriptClassName Blue
hi! link purescriptImport Cyan
hi! link purescriptAsKeyword Purple
hi! link purescriptImportAs Blue
hi! link purescriptWhere Purple
hi! link javaScopeDecl Red
hi! link javaTypedef Cyan
hi! link javaAnnotation Blue
hi! link ktStructure Red
hi! link ktAnnotation Blue
hi! link ktKeyword Blue
hi! link ktArrow Blue
hi! link pythonNone Yellow
hi! link pythonExClass Blue
hi! link pythonDecorator Red
hi! link pythonDottedName Red
hi! link goPackage Red
hi! link goImport Red
hi! link goDeclType Blue
hi! link goBuiltins Blue
hi! link rustModPath Purple
hi! link rustAttribute Purple
hi! link rustPubScopeCrate Green
hi! link rustStructure Purple
hi! link rustSigil Blue
hi! link rustSelf Cyan
hi! link rustEnumVariant Blue
hi! link rustDerive Purple
hi! link rustDeriveTrait Red
hi! link phpUseClass Blue
hi! link phpClass Purple
hi! link phpClassExtends Blue
hi! link phpParent Fg
hi! link phpFunction Blue
hi! link phpType Purple
hi! link phpMethod Yellow
hi! link phpMemberSelector Green
hi! link csUnspecifiedStatement Red
hi! link csEndColon Fg
hi! link csBraces Fg
hi! link csParens Fg
hi! link csClass Red
hi! link csType Red
hi! link csNewType Yellow
hi! link csClassType Blue
hi! link csAsync Red
hi! link csLogicSymbols Blue
hi! link csLabel Blue
hi! link fsharpOpen Purple
hi! link fsharpModule Blue
hi! link fsharpSymbol Cyan
hi! link fsharpCoreClass Blue
hi! link fsharpException Purple
hi! link fsharpScript Purple
hi! link fsharpAttrib Purple
hi! link fsharpAttribute Blue
hi! link swiftStructure Purple
hi! link swiftAttributes Purple
hi! link rubyModule Purple
hi! link rubyModuleName Red
hi! link rubyClassName Blue
hi! link rubyConstant Cyan
hi! link rubyAttribute Purple
hi! link rubyInstanceVariable Yellow
hi! link rubyAccess Purple
hi! link perlPackageDecl Blue
hi! link perlStatementPackage Red
hi! link perlFunction Purple
hi! link perlStatementInclude Red
hi! link podCommand Red
hi! link podVerbatimLine Green
hi! link podCmdText Purple
hi! link perlStatementStorage Red
hi! link perlStatementHash Red
hi! link perlStatementList Green
hi! link perlStatementIndirObj Fg
hi! link perlMethod Yellow
hi! link perlPackageRef Blue
hi! link haskellDeclKeyword Red
hi! link haskellType Blue
hi! link haskellDecl Purple
hi! link haskellPreProc Purple
hi! link haskellWhere Red
hi! link haskellOperators Purple
hi! link luaLocal Red
hi! link luaBraces Fg
hi! link luaSpecialTable Blue
hi! link luaSpecialValue Yellow
hi! link luaFuncCall Blue
hi! link luaFuncKeyword Purple
hi! link luaFuncTable Cyan
hi! link moonLuaFunc Purple
hi! link moonSpecialOp Fg
hi! link moonObject Blue
hi! link moonInterpDelim Cyan
hi! link dImport Purple
hi! link dStructure Red
hi! link dEnum Purple
hi! link dScopeDecl Red
hi! link dAnnotation Blue
hi! link dAttribute Blue
hi! link scalaCapitalWord Purple
hi! link scalaKeywordModifier Purple
hi! link scalaInstanceDeclaration Blue
hi! link scalaSpecial Purple
hi! link scalaSquareBracketsBrackets Fg
hi! link scalaTypeDeclaration Yellow
hi! link elixirModuleDeclaration Purple
hi! link elixirInclude Purple
hi! link elixirAlias Blue
hi! link elixirVariable Yellow
hi! link elixirPseudoVariable Yellow
hi! link elixirDefine Purple
hi! link elixirMacroDeclaration Purple
hi! link elixirModuleDefine Purple
hi! link elixirProtocolDefine Purple
hi! link elixirImplDefine Purple
hi! link elixirRecordDefine Purple
hi! link elixirPrivateRecordDefine Purple
hi! link elixirMacroDefine Purple
hi! link elixirPrivateMacroDefine Purple
hi! link elixirDelegateDefine Purple
hi! link elixirOverridableDefine Purple
hi! link elixirExceptionDefine Purple
hi! link elixirCallbackDefine Purple
hi! link elixirStructDefine Purple
hi! link ocamlModule Blue
hi! link ocamlEqual Blue
hi! link ocamlPpxEncl Purple
hi! link ocamlArrow Blue
hi! link ocamlModPath Purple
hi! link ocamlKeyChar Blue
hi! link ocamlFullMod Purple
hi! link ocamlFuncWith Fg
hi! link ocamlWith Blue
hi! link ocamlModParam1 Green
hi! link ocamlModPreRHS Fg
hi! link ocamlConstructor Green
hi! link clojureDefine Purple
hi! link clojureQuote Fg
hi! link clojureSpecial Purple
hi! link clojureDispatch Yellow
hi! link clojureVariable Green
hi! link erlangType Purple
hi! link erlangLocalFuncCall Blue
hi! link erlangLocalFuncRef Yellow
hi! link erlangGlobalFuncCall Purple
hi! link juliaBlKeyword Purple
hi! link lispDecl Red
hi! link lispKey Blue
hi! link shCommandSub Red
hi! link shDerefSimple Blue
hi! link shDerefVar Yellow
hi! link shQuote Green
hi! link shFunction Red
hi! link zshOptStart Purple
hi! link zshOption Blue
hi! link zshSubst Yellow
hi! link zshFunction Purple
hi! link zshDeref Blue
hi! link zshTypes Purple
hi! link fishIdentifier Blue
hi! link vimFunction Blue
hi! link vimLet Red
hi! link vimMap Blue
hi! link vimMapMod Yellow
hi! link vimMapLhs Green
hi! link vimMapRhs Green
hi! link vimNotation Purple
hi! link vimAugroupKey Red
hi! link vimAutoCmd Blue
hi! link jsonKeyword Blue
hi! link yamlKey Blue
hi! link tomlKey Blue
hi! link diffAdded Green
hi! link diffRemoved Red
hi! link diffChanged Yellow
hi! link diffOldFile Blue
hi! link diffNewFile Purple
hi! link diffFile Green
hi! link diffLine Grey
hi! link diffIndexLine Cyan
hi! link helpHyperTextEntry Blue
hi! link helpHyperTextJump Red
hi! link helpSectionDelim Grey
hi! link helpExample Green
hi! link helpCommand Purple
hi! link helpHeadline Purple
hi! link helpHeader Blue

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#b7bec9', '#e77171', '#a1bf78', '#dbb774',
          \ '#73b3e7', '#d390e7', '#5ebaa5', '#88909f', '#b7bec9', '#e77171',
          \ '#a1bf78', '#dbb774', '#73b3e7', '#d390e7', '#5ebaa5', '#88909f']
    if has('nvim')
      let g:terminal_color_0 = '#b7bec9'
      let g:terminal_color_1 = '#e77171'
      let g:terminal_color_2 = '#a1bf78'
      let g:terminal_color_3 = '#dbb774'
      let g:terminal_color_4 = '#73b3e7'
      let g:terminal_color_5 = '#d390e7'
      let g:terminal_color_6 = '#5ebaa5'
      let g:terminal_color_7 = '#88909f'
      let g:terminal_color_8 = '#b7bec9'
      let g:terminal_color_9 = '#e77171'
      let g:terminal_color_10 = '#a1bf78'
      let g:terminal_color_11 = '#dbb774'
      let g:terminal_color_12 = '#73b3e7'
      let g:terminal_color_13 = '#d390e7'
      let g:terminal_color_14 = '#5ebaa5'
      let g:terminal_color_15 = '#88909f'
    endif
    hi Fg guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Red guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Yellow guifg=#dbb774 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Green guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Cyan guifg=#5ebaa5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Blue guifg=#73b3e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Purple guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Grey guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    if get(g:, 'dark_and_light_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#b7bec9 guibg=#262729 guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#b7bec9 guibg=#262729 guisp=NONE gui=NONE cterm=NONE
    endif
    hi ColorColumn guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi Conceal guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorColumn guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#b7bec9 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#88909f guibg=#262729 guisp=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=NONE guibg=#293323 guisp=NONE gui=NONE cterm=NONE
    hi DiffChange guifg=NONE guibg=#1e232d guisp=NONE gui=NONE cterm=NONE
    hi DiffDelete guifg=NONE guibg=#362023 guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=NONE guibg=#262729 guisp=NONE gui=reverse cterm=reverse
    hi Directory guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi EndOfBuffer guifg=#262729 guibg=#262729 guisp=NONE gui=NONE cterm=NONE
    hi ErrorMsg guifg=#e77171 guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
    hi WarningMsg guifg=#dbb774 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi ModeMsg guifg=#73b3e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi MoreMsg guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi FoldColumn guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi IncSearch guifg=NONE guibg=#3e4249 guisp=NONE gui=underline cterm=underline
    hi Search guifg=NONE guibg=#3e4249 guisp=NONE gui=underline cterm=underline
    hi MatchParen guifg=NONE guibg=#3e4249 guisp=NONE gui=bold cterm=bold
    hi NonText guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=#b7bec9 guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#262729 guibg=#73b3e7 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guifg=NONE guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guifg=NONE guibg=#88909f guisp=NONE gui=NONE cterm=NONE
    hi Question guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=#e77171 guibg=NONE guisp=#e77171 gui=NONE cterm=NONE
    hi SpellCap guifg=#dbb774 guibg=NONE guisp=#dbb774 gui=NONE cterm=NONE
    hi SpellLocal guifg=#73b3e7 guibg=NONE guisp=#73b3e7 gui=NONE cterm=NONE
    hi SpellRare guifg=#d390e7 guibg=NONE guisp=#d390e7 gui=NONE cterm=NONE
    hi StatusLine guifg=#b7bec9 guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi TabLine guifg=#b7bec9 guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=#262729 guibg=#d390e7 guisp=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#3e4249 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi VisualNOS guifg=NONE guibg=#3e4249 guisp=NONE gui=italic cterm=italic
    hi WildMenu guifg=#262729 guibg=#a1bf78 guisp=NONE gui=NONE cterm=NONE
    hi CursorIM guifg=NONE guibg=#b7bec9 guisp=NONE gui=NONE cterm=NONE
    hi ToolbarLine guifg=NONE guibg=#88909f guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#b7bec9 guibg=#262729 guisp=NONE gui=bold cterm=bold
    hi! link QuickFixLine Search
    hi! link lCursor Cursor
    hi! link StatusLineTerm StatusLine
    hi! link StatusLineTermNC StatusLineNC
    hi PreProc guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Macro guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Error guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Keyword guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Define guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Typedef guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Exception guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Label guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#dbb774 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Type guifg=#dbb774 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Structure guifg=#dbb774 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Boolean guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi String guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Character guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Number guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Float guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Identifier guifg=#5ebaa5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Constant guifg=#5ebaa5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Function guifg=#73b3e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Operator guifg=#73b3e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#73b3e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Conditional guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PreCondit guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Repeat guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Todo guifg=#d390e7 guibg=NONE guisp=NONE gui=italic cterm=italic
    hi StorageClass guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Statement guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Tag guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Delimiter guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Comment guifg=#88909f guibg=NONE guisp=NONE gui=italic cterm=italic
    hi SpecialComment guifg=#88909f guibg=NONE guisp=NONE gui=italic cterm=italic
    hi Ignore guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi! link SpecialChar Special
    hi! link Debug Special
    hi! link Include PreProc
    hi plug1 guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi plugNumber guifg=#a1bf78 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi GitGutterAdd guifg=#a1bf78 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi GitGutterChange guifg=#dbb774 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi GitGutterDelete guifg=#e77171 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi GitGutterChangeDelete guifg=#d390e7 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi SignifySignAdd guifg=#a1bf78 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi SignifySignChange guifg=#dbb774 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi SignifySignDelete guifg=#e77171 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi SyntasticError guifg=NONE guibg=NONE guisp=#e77171 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SyntasticWarning guifg=NONE guibg=NONE guisp=#dbb774 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SyntasticErrorSign guifg=#e77171 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi SyntasticWarningSign guifg=#dbb774 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi Lf_hl_match guifg=#a1bf78 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Lf_hl_match0 guifg=#a1bf78 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Lf_hl_match1 guifg=#5ebaa5 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Lf_hl_match2 guifg=#73b3e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Lf_hl_match3 guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Lf_hl_match4 guifg=#e77171 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Lf_hl_matchRefine guifg=#dbb774 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi ALEError guifg=NONE guibg=NONE guisp=#e77171 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi ALEWarning guifg=NONE guibg=NONE guisp=#dbb774 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi ALEInfo guifg=NONE guibg=NONE guisp=#73b3e7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi ALEErrorSign guifg=#e77171 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi ALEWarningSign guifg=#dbb774 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi ALEInfoSign guifg=#73b3e7 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi CocHoverRange guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
    hi multiple_cursors_cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi multiple_cursors_visual guifg=NONE guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi UndotreeSavedBig guifg=#e77171 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi markdownH1 guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi markdownH2 guifg=#e77171 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi markdownH3 guifg=#dbb774 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi markdownH4 guifg=#73b3e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi markdownH5 guifg=#5ebaa5 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi markdownH6 guifg=#a1bf78 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi markdownUrl guifg=#a1bf78 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi markdownItalicDelimiter guifg=#88909f guibg=NONE guisp=NONE gui=italic cterm=italic
    hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi mkdURL guifg=#a1bf78 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi mkdItalic guifg=#88909f guibg=NONE guisp=NONE gui=italic cterm=italic
    hi rstStandaloneHyperlink guifg=#a1bf78 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi rstSections guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi htmlH1 guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi htmlH2 guifg=#e77171 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi htmlH3 guifg=#dbb774 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi htmlH4 guifg=#73b3e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi htmlH5 guifg=#5ebaa5 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi htmlH6 guifg=#a1bf78 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi htmlBoldUnderline guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
    hi htmlBoldItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
    hi htmlBoldUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic,underline ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
    hi htmlUnderline guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi htmlUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=italic,underline ctermfg=NONE ctermbg=NONE cterm=italic,underline
    hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi helpURL guifg=#5ebaa5 guibg=NONE guisp=NONE gui=underline cterm=underline
    hi helpNote guifg=#e77171 guibg=NONE guisp=NONE gui=bold cterm=bold
    if !s:italics
      hi VisualNOS gui=NONE cterm=NONE
      hi Todo gui=NONE cterm=NONE
      hi Comment gui=NONE cterm=NONE
      hi SpecialComment gui=NONE cterm=NONE
      hi markdownItalicDelimiter gui=NONE cterm=NONE
      hi markdownItalic gui=NONE cterm=NONE
      hi mkdItalic gui=NONE cterm=NONE
      hi htmlBoldItalic gui=bold cterm=bold
      hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
      hi htmlUnderlineItalic gui=underline cterm=underline
      hi htmlItalic gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#5e646f', '#db7070', '#7c9f4b', '#d69822',
        \ '#6587bf', '#b870ce', '#509c93', '#949ba5', '#5e646f', '#db7070',
        \ '#7c9f4b', '#d69822', '#6587bf', '#b870ce', '#509c93', '#949ba5']
  if has('nvim')
    let g:terminal_color_0 = '#5e646f'
    let g:terminal_color_1 = '#db7070'
    let g:terminal_color_2 = '#7c9f4b'
    let g:terminal_color_3 = '#d69822'
    let g:terminal_color_4 = '#6587bf'
    let g:terminal_color_5 = '#b870ce'
    let g:terminal_color_6 = '#509c93'
    let g:terminal_color_7 = '#949ba5'
    let g:terminal_color_8 = '#5e646f'
    let g:terminal_color_9 = '#db7070'
    let g:terminal_color_10 = '#7c9f4b'
    let g:terminal_color_11 = '#d69822'
    let g:terminal_color_12 = '#6587bf'
    let g:terminal_color_13 = '#b870ce'
    let g:terminal_color_14 = '#509c93'
    let g:terminal_color_15 = '#949ba5'
  endif
  hi Fg guifg=#5e646f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Red guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Yellow guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Green guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cyan guifg=#509c93 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Blue guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Purple guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Grey guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'dark_and_light_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#5e646f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#5e646f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#5e646f guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#5e646f guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#5e646f guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#949ba5 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#e5f4de guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#e6edf9 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#f4e2e3 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#fafafa guisp=NONE gui=reverse cterm=reverse
  hi Directory guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#fafafa guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#db7070 guibg=NONE guisp=NONE gui=bold,underline cterm=bold,underline
  hi WarningMsg guifg=#d69822 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#6587bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#949ba5 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#949ba5 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#e6eaee guisp=NONE gui=underline cterm=underline
  hi Search guifg=NONE guibg=#e6eaee guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=#e6eaee guisp=NONE gui=bold cterm=bold
  hi NonText guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#5e646f guibg=#e6eaee guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#fafafa guibg=#6587bf guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#e6eaee guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#949ba5 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#db7070 guibg=NONE guisp=#db7070 gui=NONE cterm=NONE
  hi SpellCap guifg=#d69822 guibg=NONE guisp=#d69822 gui=NONE cterm=NONE
  hi SpellLocal guifg=#6587bf guibg=NONE guisp=#6587bf gui=NONE cterm=NONE
  hi SpellRare guifg=#b870ce guibg=NONE guisp=#b870ce gui=NONE cterm=NONE
  hi StatusLine guifg=#5e646f guibg=#e6eaee guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#949ba5 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#5e646f guibg=#e6eaee guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#949ba5 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#fafafa guibg=#b870ce guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#e6eaee guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#e6eaee guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#e6eaee guisp=NONE gui=italic cterm=italic
  hi WildMenu guifg=#fafafa guibg=#7c9f4b guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=#5e646f guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#949ba5 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#5e646f guibg=#fafafa guisp=NONE gui=bold cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi PreProc guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#509c93 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#509c93 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Conditional guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#b870ce guibg=NONE guisp=NONE gui=italic cterm=italic
  hi StorageClass guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#5e646f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#949ba5 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#949ba5 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  hi plug1 guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi plugNumber guifg=#7c9f4b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi GitGutterAdd guifg=#7c9f4b guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#d69822 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#db7070 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#b870ce guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignAdd guifg=#7c9f4b guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignChange guifg=#d69822 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi SignifySignDelete guifg=#db7070 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi SyntasticError guifg=NONE guibg=NONE guisp=#db7070 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SyntasticWarning guifg=NONE guibg=NONE guisp=#d69822 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SyntasticErrorSign guifg=#db7070 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi SyntasticWarningSign guifg=#d69822 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi Lf_hl_match guifg=#7c9f4b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match0 guifg=#7c9f4b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match1 guifg=#509c93 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match2 guifg=#6587bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match3 guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_match4 guifg=#db7070 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Lf_hl_matchRefine guifg=#d69822 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ALEError guifg=NONE guibg=NONE guisp=#db7070 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEWarning guifg=NONE guibg=NONE guisp=#d69822 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEInfo guifg=NONE guibg=NONE guisp=#6587bf gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi ALEErrorSign guifg=#db7070 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#d69822 guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#6587bf guibg=#eef1f4 guisp=NONE gui=NONE cterm=NONE
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHoverRange guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi multiple_cursors_cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual guifg=NONE guibg=#e6eaee guisp=NONE gui=NONE cterm=NONE
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig guifg=#db7070 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH1 guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH2 guifg=#db7070 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH3 guifg=#d69822 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH4 guifg=#6587bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH5 guifg=#509c93 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownH6 guifg=#7c9f4b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownUrl guifg=#7c9f4b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownItalicDelimiter guifg=#949ba5 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi mkdURL guifg=#7c9f4b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdItalic guifg=#949ba5 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi rstStandaloneHyperlink guifg=#7c9f4b guibg=NONE guisp=NONE gui=underline cterm=underline
  hi rstSections guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH1 guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH2 guifg=#db7070 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH3 guifg=#d69822 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH4 guifg=#6587bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH5 guifg=#509c93 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlH6 guifg=#7c9f4b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline guifg=NONE guibg=NONE guisp=NONE gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=bold,italic,underline ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic guifg=NONE guibg=NONE guisp=NONE gui=italic,underline ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi helpURL guifg=#509c93 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi helpNote guifg=#db7070 guibg=NONE guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
    hi markdownItalicDelimiter gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
    hi mkdItalic gui=NONE cterm=NONE
    hi htmlBoldItalic gui=bold cterm=bold
    hi htmlBoldUnderlineItalic gui=bold,underline cterm=bold,underline
    hi htmlUnderlineItalic gui=underline cterm=underline
    hi htmlItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Fg ctermfg=250 ctermbg=NONE cterm=NONE
    hi Red ctermfg=203 ctermbg=NONE cterm=NONE
    hi Yellow ctermfg=179 ctermbg=NONE cterm=NONE
    hi Green ctermfg=107 ctermbg=NONE cterm=NONE
    hi Cyan ctermfg=72 ctermbg=NONE cterm=NONE
    hi Blue ctermfg=110 ctermbg=NONE cterm=NONE
    hi Purple ctermfg=176 ctermbg=NONE cterm=NONE
    hi Grey ctermfg=246 ctermbg=NONE cterm=NONE
    if get(g:, 'dark_and_light_transp_bg', 0)
      hi Normal ctermfg=250 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=250 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=250 ctermbg=235 cterm=NONE
      if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
        set background=dark
      endif
      hi Terminal ctermfg=250 ctermbg=235 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi Conceal ctermfg=246 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorLineNr ctermfg=250 ctermbg=236 cterm=NONE
    hi LineNr ctermfg=246 ctermbg=235 cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=236 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=235 cterm=NONE
    hi DiffDelete ctermfg=NONE ctermbg=235 cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=235 cterm=reverse
    hi Directory ctermfg=107 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=235 ctermbg=235 cterm=NONE
    hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=bold,underline
    hi WarningMsg ctermfg=179 ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=110 ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=176 ctermbg=NONE cterm=bold
    hi FoldColumn ctermfg=246 ctermbg=236 cterm=NONE
    hi Folded ctermfg=246 ctermbg=236 cterm=NONE
    hi IncSearch ctermfg=NONE ctermbg=238 cterm=underline
    hi Search ctermfg=NONE ctermbg=238 cterm=underline
    hi MatchParen ctermfg=NONE ctermbg=238 cterm=bold
    hi NonText ctermfg=246 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=250 ctermbg=238 cterm=NONE
    hi PmenuSel ctermfg=235 ctermbg=110 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=238 cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=246 cterm=NONE
    hi Question ctermfg=107 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=203 ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=179 ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=110 ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=176 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=250 ctermbg=238 cterm=NONE
    hi StatusLineNC ctermfg=246 ctermbg=236 cterm=NONE
    hi TabLine ctermfg=250 ctermbg=238 cterm=NONE
    hi TabLineFill ctermfg=246 ctermbg=236 cterm=NONE
    hi TabLineSel ctermfg=235 ctermbg=176 cterm=NONE
    hi VertSplit ctermfg=238 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=238 cterm=italic
    hi WildMenu ctermfg=235 ctermbg=107 cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=250 cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=246 cterm=NONE
    hi ToolbarButton ctermfg=250 ctermbg=235 cterm=bold
    hi! link QuickFixLine Search
    hi! link lCursor Cursor
    hi! link StatusLineTerm StatusLine
    hi! link StatusLineTermNC StatusLineNC
    hi PreProc ctermfg=203 ctermbg=NONE cterm=NONE
    hi Macro ctermfg=203 ctermbg=NONE cterm=NONE
    hi Error ctermfg=203 ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=203 ctermbg=NONE cterm=NONE
    hi Define ctermfg=203 ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=203 ctermbg=NONE cterm=NONE
    hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
    hi Label ctermfg=203 ctermbg=NONE cterm=NONE
    hi Special ctermfg=179 ctermbg=NONE cterm=NONE
    hi Type ctermfg=179 ctermbg=NONE cterm=NONE
    hi Structure ctermfg=179 ctermbg=NONE cterm=NONE
    hi Boolean ctermfg=107 ctermbg=NONE cterm=NONE
    hi String ctermfg=107 ctermbg=NONE cterm=NONE
    hi Character ctermfg=107 ctermbg=NONE cterm=NONE
    hi Number ctermfg=107 ctermbg=NONE cterm=NONE
    hi Float ctermfg=107 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=72 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=72 ctermbg=NONE cterm=NONE
    hi Function ctermfg=110 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=110 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=110 ctermbg=NONE cterm=NONE
    hi Title ctermfg=176 ctermbg=NONE cterm=bold
    hi Conditional ctermfg=176 ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=176 ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=176 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=176 ctermbg=NONE cterm=italic
    hi StorageClass ctermfg=176 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=176 ctermbg=NONE cterm=NONE
    hi Tag ctermfg=176 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=250 ctermbg=NONE cterm=NONE
    hi Comment ctermfg=246 ctermbg=NONE cterm=italic
    hi SpecialComment ctermfg=246 ctermbg=NONE cterm=italic
    hi Ignore ctermfg=246 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi! link SpecialChar Special
    hi! link Debug Special
    hi! link Include PreProc
    hi plug1 ctermfg=176 ctermbg=NONE cterm=bold
    hi plugNumber ctermfg=107 ctermbg=NONE cterm=bold
    hi GitGutterAdd ctermfg=107 ctermbg=236 cterm=NONE
    hi GitGutterChange ctermfg=179 ctermbg=236 cterm=NONE
    hi GitGutterDelete ctermfg=203 ctermbg=236 cterm=NONE
    hi GitGutterChangeDelete ctermfg=176 ctermbg=236 cterm=NONE
    hi SignifySignAdd ctermfg=107 ctermbg=236 cterm=NONE
    hi SignifySignChange ctermfg=179 ctermbg=236 cterm=NONE
    hi SignifySignDelete ctermfg=203 ctermbg=236 cterm=NONE
    hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticErrorSign ctermfg=203 ctermbg=236 cterm=NONE
    hi SyntasticWarningSign ctermfg=179 ctermbg=236 cterm=NONE
    hi Lf_hl_match ctermfg=107 ctermbg=NONE cterm=bold
    hi Lf_hl_match0 ctermfg=107 ctermbg=NONE cterm=bold
    hi Lf_hl_match1 ctermfg=72 ctermbg=NONE cterm=bold
    hi Lf_hl_match2 ctermfg=110 ctermbg=NONE cterm=bold
    hi Lf_hl_match3 ctermfg=176 ctermbg=NONE cterm=bold
    hi Lf_hl_match4 ctermfg=203 ctermbg=NONE cterm=bold
    hi Lf_hl_matchRefine ctermfg=179 ctermbg=NONE cterm=bold
    hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEErrorSign ctermfg=203 ctermbg=236 cterm=NONE
    hi ALEWarningSign ctermfg=179 ctermbg=236 cterm=NONE
    hi ALEInfoSign ctermfg=110 ctermbg=236 cterm=NONE
    hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
    hi CocHoverRange ctermfg=NONE ctermbg=NONE cterm=bold,underline
    hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi multiple_cursors_visual ctermfg=NONE ctermbg=238 cterm=NONE
    hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
    hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
    hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
    hi UndotreeSavedBig ctermfg=203 ctermbg=NONE cterm=bold
    hi markdownH1 ctermfg=176 ctermbg=NONE cterm=bold
    hi markdownH2 ctermfg=203 ctermbg=NONE cterm=bold
    hi markdownH3 ctermfg=179 ctermbg=NONE cterm=bold
    hi markdownH4 ctermfg=110 ctermbg=NONE cterm=bold
    hi markdownH5 ctermfg=72 ctermbg=NONE cterm=bold
    hi markdownH6 ctermfg=107 ctermbg=NONE cterm=bold
    hi markdownUrl ctermfg=107 ctermbg=NONE cterm=underline
    hi markdownItalicDelimiter ctermfg=246 ctermbg=NONE cterm=italic
    hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
    hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
    hi mkdURL ctermfg=107 ctermbg=NONE cterm=underline
    hi mkdItalic ctermfg=246 ctermbg=NONE cterm=italic
    hi rstStandaloneHyperlink ctermfg=107 ctermbg=NONE cterm=underline
    hi rstSections ctermfg=176 ctermbg=NONE cterm=bold
    hi htmlH1 ctermfg=176 ctermbg=NONE cterm=bold
    hi htmlH2 ctermfg=203 ctermbg=NONE cterm=bold
    hi htmlH3 ctermfg=179 ctermbg=NONE cterm=bold
    hi htmlH4 ctermfg=110 ctermbg=NONE cterm=bold
    hi htmlH5 ctermfg=72 ctermbg=NONE cterm=bold
    hi htmlH6 ctermfg=107 ctermbg=NONE cterm=bold
    hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
    hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
    hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
    hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
    hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
    hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
    hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
    hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
    hi helpURL ctermfg=72 ctermbg=NONE cterm=underline
    hi helpNote ctermfg=203 ctermbg=NONE cterm=bold
    if !s:italics
      hi VisualNOS cterm=NONE
      hi Todo cterm=NONE
      hi Comment cterm=NONE
      hi SpecialComment cterm=NONE
      hi markdownItalicDelimiter cterm=NONE
      hi markdownItalic cterm=NONE
      hi mkdItalic cterm=NONE
      hi htmlBoldItalic cterm=bold
      hi htmlBoldUnderlineItalic cterm=bold,underline
      hi htmlUnderlineItalic cterm=underline
      hi htmlItalic cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Fg ctermfg=241 ctermbg=NONE cterm=NONE
  hi Red ctermfg=167 ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=172 ctermbg=NONE cterm=NONE
  hi Green ctermfg=107 ctermbg=NONE cterm=NONE
  hi Cyan ctermfg=73 ctermbg=NONE cterm=NONE
  hi Blue ctermfg=68 ctermbg=NONE cterm=NONE
  hi Purple ctermfg=134 ctermbg=NONE cterm=NONE
  hi Grey ctermfg=247 ctermbg=NONE cterm=NONE
  if get(g:, 'dark_and_light_transp_bg', 0)
    hi Normal ctermfg=241 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=241 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=241 ctermbg=231 cterm=NONE
    hi Terminal ctermfg=241 ctermbg=231 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi Conceal ctermfg=247 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=241 ctermbg=255 cterm=NONE
  hi LineNr ctermfg=247 ctermbg=231 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=230 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=255 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=224 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=231 cterm=reverse
  hi Directory ctermfg=107 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=231 ctermbg=231 cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=NONE cterm=bold,underline
  hi WarningMsg ctermfg=172 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=68 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=134 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=247 ctermbg=255 cterm=NONE
  hi Folded ctermfg=247 ctermbg=255 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=254 cterm=underline
  hi Search ctermfg=NONE ctermbg=254 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=254 cterm=bold
  hi NonText ctermfg=247 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=241 ctermbg=254 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=68 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=254 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=247 cterm=NONE
  hi Question ctermfg=107 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=172 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=68 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=134 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=241 ctermbg=254 cterm=NONE
  hi StatusLineNC ctermfg=247 ctermbg=255 cterm=NONE
  hi TabLine ctermfg=241 ctermbg=254 cterm=NONE
  hi TabLineFill ctermfg=247 ctermbg=255 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=134 cterm=NONE
  hi VertSplit ctermfg=254 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=254 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=254 cterm=italic
  hi WildMenu ctermfg=231 ctermbg=107 cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=241 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=247 cterm=NONE
  hi ToolbarButton ctermfg=241 ctermbg=231 cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi PreProc ctermfg=167 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=167 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi Define ctermfg=167 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=167 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=167 ctermbg=NONE cterm=NONE
  hi Label ctermfg=167 ctermbg=NONE cterm=NONE
  hi Special ctermfg=172 ctermbg=NONE cterm=NONE
  hi Type ctermfg=172 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=172 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=107 ctermbg=NONE cterm=NONE
  hi String ctermfg=107 ctermbg=NONE cterm=NONE
  hi Character ctermfg=107 ctermbg=NONE cterm=NONE
  hi Number ctermfg=107 ctermbg=NONE cterm=NONE
  hi Float ctermfg=107 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=73 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=73 ctermbg=NONE cterm=NONE
  hi Function ctermfg=68 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=68 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=68 ctermbg=NONE cterm=NONE
  hi Title ctermfg=134 ctermbg=NONE cterm=bold
  hi Conditional ctermfg=134 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=134 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=134 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=134 ctermbg=NONE cterm=italic
  hi StorageClass ctermfg=134 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=134 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=134 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=241 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=247 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=247 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=247 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  hi plug1 ctermfg=134 ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=107 ctermbg=NONE cterm=bold
  hi GitGutterAdd ctermfg=107 ctermbg=255 cterm=NONE
  hi GitGutterChange ctermfg=172 ctermbg=255 cterm=NONE
  hi GitGutterDelete ctermfg=167 ctermbg=255 cterm=NONE
  hi GitGutterChangeDelete ctermfg=134 ctermbg=255 cterm=NONE
  hi SignifySignAdd ctermfg=107 ctermbg=255 cterm=NONE
  hi SignifySignChange ctermfg=172 ctermbg=255 cterm=NONE
  hi SignifySignDelete ctermfg=167 ctermbg=255 cterm=NONE
  hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticErrorSign ctermfg=167 ctermbg=255 cterm=NONE
  hi SyntasticWarningSign ctermfg=172 ctermbg=255 cterm=NONE
  hi Lf_hl_match ctermfg=107 ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=107 ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=73 ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=68 ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=134 ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=167 ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=172 ctermbg=NONE cterm=bold
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=167 ctermbg=255 cterm=NONE
  hi ALEWarningSign ctermfg=172 ctermbg=255 cterm=NONE
  hi ALEInfoSign ctermfg=68 ctermbg=255 cterm=NONE
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHoverRange ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=254 cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig ctermfg=167 ctermbg=NONE cterm=bold
  hi markdownH1 ctermfg=134 ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=167 ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=172 ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=68 ctermbg=NONE cterm=bold
  hi markdownH5 ctermfg=73 ctermbg=NONE cterm=bold
  hi markdownH6 ctermfg=107 ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=107 ctermbg=NONE cterm=underline
  hi markdownItalicDelimiter ctermfg=247 ctermbg=NONE cterm=italic
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi mkdURL ctermfg=107 ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=247 ctermbg=NONE cterm=italic
  hi rstStandaloneHyperlink ctermfg=107 ctermbg=NONE cterm=underline
  hi rstSections ctermfg=134 ctermbg=NONE cterm=bold
  hi htmlH1 ctermfg=134 ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=167 ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=172 ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=68 ctermbg=NONE cterm=bold
  hi htmlH5 ctermfg=73 ctermbg=NONE cterm=bold
  hi htmlH6 ctermfg=107 ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi helpURL ctermfg=73 ctermbg=NONE cterm=underline
  hi helpNote ctermfg=167 ctermbg=NONE cterm=bold
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi markdownItalic cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'dark_and_light_transp_bg', 0)
      hi Normal ctermfg=White ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=White ctermbg=Black cterm=NONE
      hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=LightGrey cterm=NONE
    hi LineNr ctermfg=Grey ctermbg=Black cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
    hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=Black cterm=reverse
    hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
    hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold,underline
    hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=Blue ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=Magenta ctermbg=NONE cterm=bold
    hi FoldColumn ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi Folded ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi IncSearch ctermfg=NONE ctermbg=LightGrey cterm=underline
    hi Search ctermfg=NONE ctermbg=LightGrey cterm=underline
    hi MatchParen ctermfg=NONE ctermbg=LightGrey cterm=bold
    hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=White ctermbg=LightGrey cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=Blue cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=Grey cterm=NONE
    hi Question ctermfg=Green ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=White ctermbg=LightGrey cterm=NONE
    hi StatusLineNC ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi TabLine ctermfg=White ctermbg=LightGrey cterm=NONE
    hi TabLineFill ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=Magenta cterm=NONE
    hi VertSplit ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=LightGrey cterm=italic
    hi WildMenu ctermfg=Black ctermbg=Green cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=Grey cterm=NONE
    hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
    hi! link QuickFixLine Search
    hi! link lCursor Cursor
    hi! link StatusLineTerm StatusLine
    hi! link StatusLineTermNC StatusLineNC
    hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
    hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
    hi Define ctermfg=Red ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
    hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
    hi Label ctermfg=Red ctermbg=NONE cterm=NONE
    hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Structure ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
    hi String ctermfg=Green ctermbg=NONE cterm=NONE
    hi Character ctermfg=Green ctermbg=NONE cterm=NONE
    hi Number ctermfg=Green ctermbg=NONE cterm=NONE
    hi Float ctermfg=Green ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Title ctermfg=Magenta ctermbg=NONE cterm=bold
    hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Todo ctermfg=Magenta ctermbg=NONE cterm=italic
    hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Statement ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Tag ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
    hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
    hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
    hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi! link SpecialChar Special
    hi! link Debug Special
    hi! link Include PreProc
    hi plug1 ctermfg=Magenta ctermbg=NONE cterm=bold
    hi plugNumber ctermfg=Green ctermbg=NONE cterm=bold
    hi GitGutterAdd ctermfg=Green ctermbg=LightGrey cterm=NONE
    hi GitGutterChange ctermfg=Yellow ctermbg=LightGrey cterm=NONE
    hi GitGutterDelete ctermfg=Red ctermbg=LightGrey cterm=NONE
    hi GitGutterChangeDelete ctermfg=Magenta ctermbg=LightGrey cterm=NONE
    hi SignifySignAdd ctermfg=Green ctermbg=LightGrey cterm=NONE
    hi SignifySignChange ctermfg=Yellow ctermbg=LightGrey cterm=NONE
    hi SignifySignDelete ctermfg=Red ctermbg=LightGrey cterm=NONE
    hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi SyntasticErrorSign ctermfg=Red ctermbg=LightGrey cterm=NONE
    hi SyntasticWarningSign ctermfg=Yellow ctermbg=LightGrey cterm=NONE
    hi Lf_hl_match ctermfg=Green ctermbg=NONE cterm=bold
    hi Lf_hl_match0 ctermfg=Green ctermbg=NONE cterm=bold
    hi Lf_hl_match1 ctermfg=Cyan ctermbg=NONE cterm=bold
    hi Lf_hl_match2 ctermfg=Blue ctermbg=NONE cterm=bold
    hi Lf_hl_match3 ctermfg=Magenta ctermbg=NONE cterm=bold
    hi Lf_hl_match4 ctermfg=Red ctermbg=NONE cterm=bold
    hi Lf_hl_matchRefine ctermfg=Yellow ctermbg=NONE cterm=bold
    hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
    hi ALEErrorSign ctermfg=Red ctermbg=LightGrey cterm=NONE
    hi ALEWarningSign ctermfg=Yellow ctermbg=LightGrey cterm=NONE
    hi ALEInfoSign ctermfg=Blue ctermbg=LightGrey cterm=NONE
    hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
    hi CocHoverRange ctermfg=NONE ctermbg=NONE cterm=bold,underline
    hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi multiple_cursors_visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
    hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
    hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
    hi UndotreeSavedBig ctermfg=Red ctermbg=NONE cterm=bold
    hi markdownH1 ctermfg=Magenta ctermbg=NONE cterm=bold
    hi markdownH2 ctermfg=Red ctermbg=NONE cterm=bold
    hi markdownH3 ctermfg=Yellow ctermbg=NONE cterm=bold
    hi markdownH4 ctermfg=Blue ctermbg=NONE cterm=bold
    hi markdownH5 ctermfg=Cyan ctermbg=NONE cterm=bold
    hi markdownH6 ctermfg=Green ctermbg=NONE cterm=bold
    hi markdownUrl ctermfg=Green ctermbg=NONE cterm=underline
    hi markdownItalicDelimiter ctermfg=Grey ctermbg=NONE cterm=italic
    hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
    hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
    hi mkdURL ctermfg=Green ctermbg=NONE cterm=underline
    hi mkdItalic ctermfg=Grey ctermbg=NONE cterm=italic
    hi rstStandaloneHyperlink ctermfg=Green ctermbg=NONE cterm=underline
    hi rstSections ctermfg=Magenta ctermbg=NONE cterm=bold
    hi htmlH1 ctermfg=Magenta ctermbg=NONE cterm=bold
    hi htmlH2 ctermfg=Red ctermbg=NONE cterm=bold
    hi htmlH3 ctermfg=Yellow ctermbg=NONE cterm=bold
    hi htmlH4 ctermfg=Blue ctermbg=NONE cterm=bold
    hi htmlH5 ctermfg=Cyan ctermbg=NONE cterm=bold
    hi htmlH6 ctermfg=Green ctermbg=NONE cterm=bold
    hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
    hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
    hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
    hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
    hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
    hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
    hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
    hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
    hi helpURL ctermfg=Cyan ctermbg=NONE cterm=underline
    hi helpNote ctermfg=Red ctermbg=NONE cterm=bold
    if !s:italics
      hi VisualNOS cterm=NONE
      hi Todo cterm=NONE
      hi Comment cterm=NONE
      hi SpecialComment cterm=NONE
      hi markdownItalicDelimiter cterm=NONE
      hi markdownItalic cterm=NONE
      hi mkdItalic cterm=NONE
      hi htmlBoldItalic cterm=bold
      hi htmlBoldUnderlineItalic cterm=bold,underline
      hi htmlUnderlineItalic cterm=underline
      hi htmlItalic cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Fg ctermfg=Black ctermbg=NONE cterm=NONE
  hi Red ctermfg=Red ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Green ctermfg=Green ctermbg=NONE cterm=NONE
  hi Cyan ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Blue ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Purple ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Grey ctermfg=Grey ctermbg=NONE cterm=NONE
  if get(g:, 'dark_and_light_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=White cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=White cterm=reverse
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=White cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold,underline
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=Blue ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=Magenta ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi Search ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=LightGrey cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Blue cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Grey cterm=NONE
  hi Question ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi StatusLineNC ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Magenta cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=LightGrey cterm=italic
  hi WildMenu ctermfg=White ctermbg=Green cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=White cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Red ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Label ctermfg=Red ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Title ctermfg=Magenta ctermbg=NONE cterm=bold
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=italic
  hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Black ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  hi plug1 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi plugNumber ctermfg=Green ctermbg=NONE cterm=bold
  hi GitGutterAdd ctermfg=Green ctermbg=LightGrey cterm=NONE
  hi GitGutterChange ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi GitGutterDelete ctermfg=Red ctermbg=LightGrey cterm=NONE
  hi GitGutterChangeDelete ctermfg=Magenta ctermbg=LightGrey cterm=NONE
  hi SignifySignAdd ctermfg=Green ctermbg=LightGrey cterm=NONE
  hi SignifySignChange ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi SignifySignDelete ctermfg=Red ctermbg=LightGrey cterm=NONE
  hi SyntasticError ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi SyntasticErrorSign ctermfg=Red ctermbg=LightGrey cterm=NONE
  hi SyntasticWarningSign ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi Lf_hl_match ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match0 ctermfg=Green ctermbg=NONE cterm=bold
  hi Lf_hl_match1 ctermfg=Cyan ctermbg=NONE cterm=bold
  hi Lf_hl_match2 ctermfg=Blue ctermbg=NONE cterm=bold
  hi Lf_hl_match3 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi Lf_hl_match4 ctermfg=Red ctermbg=NONE cterm=bold
  hi Lf_hl_matchRefine ctermfg=Yellow ctermbg=NONE cterm=bold
  hi ALEError ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEWarning ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEInfo ctermfg=NONE ctermbg=NONE cterm=underline
  hi ALEErrorSign ctermfg=Red ctermbg=LightGrey cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=LightGrey cterm=NONE
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocHoverRange ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi multiple_cursors_cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi multiple_cursors_visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi UndotreeSavedBig ctermfg=Red ctermbg=NONE cterm=bold
  hi markdownH1 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi markdownH2 ctermfg=Red ctermbg=NONE cterm=bold
  hi markdownH3 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi markdownH4 ctermfg=Blue ctermbg=NONE cterm=bold
  hi markdownH5 ctermfg=Cyan ctermbg=NONE cterm=bold
  hi markdownH6 ctermfg=Green ctermbg=NONE cterm=bold
  hi markdownUrl ctermfg=Green ctermbg=NONE cterm=underline
  hi markdownItalicDelimiter ctermfg=Grey ctermbg=NONE cterm=italic
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi mkdURL ctermfg=Green ctermbg=NONE cterm=underline
  hi mkdItalic ctermfg=Grey ctermbg=NONE cterm=italic
  hi rstStandaloneHyperlink ctermfg=Green ctermbg=NONE cterm=underline
  hi rstSections ctermfg=Magenta ctermbg=NONE cterm=bold
  hi htmlH1 ctermfg=Magenta ctermbg=NONE cterm=bold
  hi htmlH2 ctermfg=Red ctermbg=NONE cterm=bold
  hi htmlH3 ctermfg=Yellow ctermbg=NONE cterm=bold
  hi htmlH4 ctermfg=Blue ctermbg=NONE cterm=bold
  hi htmlH5 ctermfg=Cyan ctermbg=NONE cterm=bold
  hi htmlH6 ctermfg=Green ctermbg=NONE cterm=bold
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlBoldUnderline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi htmlBoldItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic
  hi htmlBoldUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=bold,italic,underline
  hi htmlUnderline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlUnderlineItalic ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi helpURL ctermfg=Cyan ctermbg=NONE cterm=underline
  hi helpNote ctermfg=Red ctermbg=NONE cterm=bold
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalicDelimiter cterm=NONE
    hi markdownItalic cterm=NONE
    hi mkdItalic cterm=NONE
    hi htmlBoldItalic cterm=bold
    hi htmlBoldUnderlineItalic cterm=bold,underline
    hi htmlUnderlineItalic cterm=underline
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: background    #262729           ~                 Black
" Color: foreground    #b7bec9           ~                 White
" Color: red           #e77171           ~                 Red
" Color: yellow        #dbb774           ~                 Yellow
" Color: green         #a1bf78           ~                 Green
" Color: cyan          #5ebaa5           ~                 Cyan
" Color: blue          #73b3e7           ~                 Blue
" Color: purple        #d390e7           ~                 Magenta
" Color: grey          #88909f           ~                 Grey
" Color: background_alt #2d2f33          ~                 LightGrey
" Color: background_grey #3e4249         ~                 LightGrey
" Color: background_red #362023          ~                 LightRed
" Color: background_green #293323        ~                 LightGreen
" Color: background_blue #1e232d         ~                 LightBlue
" Term colors: foreground red green yellow blue purple cyan grey
" Term colors: foreground red green yellow blue purple cyan grey
" Background: light
" Color: background    #fafafa           ~                 White
" Color: foreground    #5e646f           ~                 Black
" Color: red           #db7070           ~                 Red
" Color: yellow        #d69822           ~                 Yellow
" Color: green         #7c9f4b           ~                 Green
" Color: cyan          #509c93           ~                 Cyan
" Color: blue          #6587bf           ~                 Blue
" Color: purple        #b870ce           ~                 Magenta
" Color: grey          #949ba5           ~                 Grey
" Color: background_alt #eef1f4          ~                 LightGrey
" Color: background_grey #e6eaee         254               LightGrey
" Color: background_red #f4e2e3          ~                 LightRed
" Color: background_green #e5f4de        ~                 LightGreen
" Color: background_blue #e6edf9         ~                 LightBlue
" Term colors: foreground red green yellow blue purple cyan grey
" Term colors: foreground red green yellow blue purple cyan grey
" Background: any
" vim: et ts=2 sw=2
