" Name:         Edge
" Description:  Material & Clean Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/edge/
" License:      MIT && Anti-996
" Last Updated: Tue 30 Jul 2019 05:10:13 PM CST

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'edge'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['fg', '#e77171', '#a1bf78', '#ddb66c',
          \ '#7dbaec', '#d390e7', '#73c19f', '#88909f', 'fg', '#e77171',
          \ '#a1bf78', '#ddb66c', '#7dbaec', '#d390e7', '#73c19f', '#88909f']
    if has('nvim')
      let g:terminal_color_0 = 'fg'
      let g:terminal_color_1 = '#e77171'
      let g:terminal_color_2 = '#a1bf78'
      let g:terminal_color_3 = '#ddb66c'
      let g:terminal_color_4 = '#7dbaec'
      let g:terminal_color_5 = '#d390e7'
      let g:terminal_color_6 = '#73c19f'
      let g:terminal_color_7 = '#88909f'
      let g:terminal_color_8 = 'fg'
      let g:terminal_color_9 = '#e77171'
      let g:terminal_color_10 = '#a1bf78'
      let g:terminal_color_11 = '#ddb66c'
      let g:terminal_color_12 = '#7dbaec'
      let g:terminal_color_13 = '#d390e7'
      let g:terminal_color_14 = '#73c19f'
      let g:terminal_color_15 = '#88909f'
    endif
    hi Fg guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Red guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Yellow guifg=#ddb66c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Green guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Cyan guifg=#73c19f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Blue guifg=#7dbaec guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Purple guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Grey guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    if get(g:, 'dark_and_light_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#b7bec9 guibg=#262729 guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#b7bec9 guibg=#262729 guisp=NONE gui=NONE cterm=NONE
    endif
    hi ColorColumn guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi Conceal guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorColumn guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#b7bec9 guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=NONE guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=NONE guibg=#293323 guisp=NONE gui=NONE cterm=NONE
    hi DiffChange guifg=NONE guibg=#1e232d guisp=NONE gui=NONE cterm=NONE
    hi DiffDelete guifg=NONE guibg=#362023 guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=NONE guibg=#2b261b guisp=NONE gui=NONE cterm=NONE
    hi Directory guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi EndOfBuffer guifg=#262729 guibg=#262729 guisp=NONE gui=NONE cterm=NONE
    hi ErrorMsg guifg=#e77171 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi WarningMsg guifg=#ddb66c guibg=NONE guisp=NONE gui=bold cterm=bold
    hi ModeMsg guifg=#7dbaec guibg=NONE guisp=NONE gui=bold cterm=bold
    hi MoreMsg guifg=#d390e7 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi FoldColumn guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi IncSearch guifg=NONE guibg=#3e4249 guisp=NONE gui=underline cterm=underline
    hi Search guifg=NONE guibg=#3e4249 guisp=NONE gui=underline cterm=underline
    hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi NonText guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=#b7bec9 guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#262729 guibg=#7dbaec guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guifg=NONE guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guifg=NONE guibg=#88909f guisp=NONE gui=NONE cterm=NONE
    hi Question guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=#e77171 guibg=NONE guisp=#e77171 gui=NONE cterm=NONE
    hi SpellCap guifg=#ddb66c guibg=NONE guisp=#ddb66c gui=NONE cterm=NONE
    hi SpellLocal guifg=#7dbaec guibg=NONE guisp=#7dbaec gui=NONE cterm=NONE
    hi SpellRare guifg=#d390e7 guibg=NONE guisp=#d390e7 gui=NONE cterm=NONE
    hi StatusLine guifg=#b7bec9 guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi TabLine guifg=#b7bec9 guibg=#3e4249 guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guifg=#88909f guibg=#2d2f33 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=#262729 guibg=#d390e7 guisp=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#3e4249 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi VisualNOS guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi WildMenu guifg=#262729 guibg=#a1bf78 guisp=NONE gui=NONE cterm=NONE
    hi CursorIM guifg=NONE guibg=#b7bec9 guisp=NONE gui=NONE cterm=NONE
    hi ToolbarLine guifg=NONE guibg=#88909f guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#b7bec9 guibg=#262729 guisp=NONE gui=bold cterm=bold
    hi! link QuickFixLine Search
    hi! link lCursor Cursor
    hi! link StatusLineTerm StatusLine
    hi! link StatusLineTermNC StatusLineNC
    hi PreProc guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Macro guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Exception guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Error guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Keyword guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Define guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Typedef guifg=#e77171 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#ddb66c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Type guifg=#ddb66c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Structure guifg=#ddb66c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Boolean guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi String guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Character guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Number guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Float guifg=#a1bf78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Identifier guifg=#73c19f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Constant guifg=#73c19f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Function guifg=#7dbaec guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Operator guifg=#7dbaec guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#7dbaec guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Label guifg=#7dbaec guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#7dbaec guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Conditional guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PreCondit guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Repeat guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Todo guifg=#d390e7 guibg=NONE guisp=NONE gui=italic cterm=italic
    hi StorageClass guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Statement guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Tag guifg=#d390e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Delimiter guifg=#b7bec9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Comment guifg=#88909f guibg=NONE guisp=NONE gui=italic cterm=italic
    hi SpecialComment guifg=#88909f guibg=NONE guisp=NONE gui=italic cterm=italic
    hi Ignore guifg=#88909f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi! link SpecialChar Special
    hi! link Debug Special
    hi! link Include PreProc
    if !s:italics
      hi Todo gui=NONE cterm=NONE
      hi Comment gui=NONE cterm=NONE
      hi SpecialComment gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['fg', '#db7070', '#7c9f4b', '#d69822',
        \ '#6587bf', '#b870ce', '#529c7d', '#949ba5', 'fg', '#db7070',
        \ '#7c9f4b', '#d69822', '#6587bf', '#b870ce', '#529c7d', '#949ba5']
  if has('nvim')
    let g:terminal_color_0 = 'fg'
    let g:terminal_color_1 = '#db7070'
    let g:terminal_color_2 = '#7c9f4b'
    let g:terminal_color_3 = '#d69822'
    let g:terminal_color_4 = '#6587bf'
    let g:terminal_color_5 = '#b870ce'
    let g:terminal_color_6 = '#529c7d'
    let g:terminal_color_7 = '#949ba5'
    let g:terminal_color_8 = 'fg'
    let g:terminal_color_9 = '#db7070'
    let g:terminal_color_10 = '#7c9f4b'
    let g:terminal_color_11 = '#d69822'
    let g:terminal_color_12 = '#6587bf'
    let g:terminal_color_13 = '#b870ce'
    let g:terminal_color_14 = '#529c7d'
    let g:terminal_color_15 = '#949ba5'
  endif
  hi Fg guifg=#656c78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Red guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Yellow guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Green guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cyan guifg=#529c7d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Blue guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Purple guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Grey guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'dark_and_light_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#656c78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#656c78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#656c78 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#656c78 guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#656c78 guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#949ba5 guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#e5f4de guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#e6edf9 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#f4e2e3 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#f4edde guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#fafafa guibg=#fafafa guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#db7070 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#d69822 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#6587bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#b870ce guibg=NONE guisp=NONE gui=bold cterm=bold
  hi FoldColumn guifg=#949ba5 guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#949ba5 guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#dde2e7 guisp=NONE gui=underline cterm=underline
  hi Search guifg=NONE guibg=#dde2e7 guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#656c78 guibg=#dde2e7 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#fafafa guibg=#6587bf guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#dde2e7 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#949ba5 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#db7070 guibg=NONE guisp=#db7070 gui=NONE cterm=NONE
  hi SpellCap guifg=#d69822 guibg=NONE guisp=#d69822 gui=NONE cterm=NONE
  hi SpellLocal guifg=#6587bf guibg=NONE guisp=#6587bf gui=NONE cterm=NONE
  hi SpellRare guifg=#b870ce guibg=NONE guisp=#b870ce gui=NONE cterm=NONE
  hi StatusLine guifg=#656c78 guibg=#dde2e7 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#949ba5 guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#656c78 guibg=#dde2e7 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#949ba5 guibg=#eceff2 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#fafafa guibg=#b870ce guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#dde2e7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu guifg=#fafafa guibg=#7c9f4b guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=#656c78 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#949ba5 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#656c78 guibg=#fafafa guisp=NONE gui=bold cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi PreProc guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#db7070 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#d69822 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#7c9f4b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#529c7d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#529c7d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#6587bf guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Label guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#6587bf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#b870ce guibg=NONE guisp=NONE gui=italic cterm=italic
  hi StorageClass guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#b870ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#656c78 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#949ba5 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#949ba5 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#949ba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  if !s:italics
    hi Todo gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Fg ctermfg=250 ctermbg=NONE cterm=NONE
    hi Red ctermfg=203 ctermbg=NONE cterm=NONE
    hi Yellow ctermfg=179 ctermbg=NONE cterm=NONE
    hi Green ctermfg=107 ctermbg=NONE cterm=NONE
    hi Cyan ctermfg=72 ctermbg=NONE cterm=NONE
    hi Blue ctermfg=110 ctermbg=NONE cterm=NONE
    hi Purple ctermfg=176 ctermbg=NONE cterm=NONE
    hi Grey ctermfg=246 ctermbg=NONE cterm=NONE
    if get(g:, 'dark_and_light_transp_bg', 0)
      hi Normal ctermfg=250 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=250 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=250 ctermbg=235 cterm=NONE
      if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
        set background=dark
      endif
      hi Terminal ctermfg=250 ctermbg=235 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi Conceal ctermfg=246 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
    hi CursorLineNr ctermfg=250 ctermbg=236 cterm=NONE
    hi LineNr ctermfg=246 ctermbg=236 cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=236 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=235 cterm=NONE
    hi DiffDelete ctermfg=NONE ctermbg=235 cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=235 cterm=NONE
    hi Directory ctermfg=107 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=235 ctermbg=235 cterm=NONE
    hi ErrorMsg ctermfg=203 ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=179 ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=110 ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=176 ctermbg=NONE cterm=bold
    hi FoldColumn ctermfg=246 ctermbg=236 cterm=NONE
    hi Folded ctermfg=246 ctermbg=236 cterm=NONE
    hi IncSearch ctermfg=NONE ctermbg=238 cterm=underline
    hi Search ctermfg=NONE ctermbg=238 cterm=underline
    hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
    hi NonText ctermfg=246 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=250 ctermbg=238 cterm=NONE
    hi PmenuSel ctermfg=235 ctermbg=110 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=238 cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=246 cterm=NONE
    hi Question ctermfg=107 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=203 ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=179 ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=110 ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=176 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=250 ctermbg=238 cterm=NONE
    hi StatusLineNC ctermfg=246 ctermbg=236 cterm=NONE
    hi TabLine ctermfg=250 ctermbg=238 cterm=NONE
    hi TabLineFill ctermfg=246 ctermbg=236 cterm=NONE
    hi TabLineSel ctermfg=235 ctermbg=176 cterm=NONE
    hi VertSplit ctermfg=238 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
    hi WildMenu ctermfg=235 ctermbg=107 cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=250 cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=246 cterm=NONE
    hi ToolbarButton ctermfg=250 ctermbg=235 cterm=bold
    hi! link QuickFixLine Search
    hi! link lCursor Cursor
    hi! link StatusLineTerm StatusLine
    hi! link StatusLineTermNC StatusLineNC
    hi PreProc ctermfg=203 ctermbg=NONE cterm=NONE
    hi Macro ctermfg=203 ctermbg=NONE cterm=NONE
    hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
    hi Error ctermfg=203 ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=203 ctermbg=NONE cterm=NONE
    hi Define ctermfg=203 ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=203 ctermbg=NONE cterm=NONE
    hi Special ctermfg=179 ctermbg=NONE cterm=NONE
    hi Type ctermfg=179 ctermbg=NONE cterm=NONE
    hi Structure ctermfg=179 ctermbg=NONE cterm=NONE
    hi Boolean ctermfg=107 ctermbg=NONE cterm=NONE
    hi String ctermfg=107 ctermbg=NONE cterm=NONE
    hi Character ctermfg=107 ctermbg=NONE cterm=NONE
    hi Number ctermfg=107 ctermbg=NONE cterm=NONE
    hi Float ctermfg=107 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=72 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=72 ctermbg=NONE cterm=NONE
    hi Function ctermfg=110 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=110 ctermbg=NONE cterm=NONE
    hi Title ctermfg=110 ctermbg=NONE cterm=bold
    hi Label ctermfg=110 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=110 ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=176 ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=176 ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=176 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=176 ctermbg=NONE cterm=italic
    hi StorageClass ctermfg=176 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=176 ctermbg=NONE cterm=NONE
    hi Tag ctermfg=176 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=250 ctermbg=NONE cterm=NONE
    hi Comment ctermfg=246 ctermbg=NONE cterm=italic
    hi SpecialComment ctermfg=246 ctermbg=NONE cterm=italic
    hi Ignore ctermfg=246 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi! link SpecialChar Special
    hi! link Debug Special
    hi! link Include PreProc
    if !s:italics
      hi Todo cterm=NONE
      hi Comment cterm=NONE
      hi SpecialComment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Fg ctermfg=242 ctermbg=NONE cterm=NONE
  hi Red ctermfg=167 ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=172 ctermbg=NONE cterm=NONE
  hi Green ctermfg=107 ctermbg=NONE cterm=NONE
  hi Cyan ctermfg=72 ctermbg=NONE cterm=NONE
  hi Blue ctermfg=68 ctermbg=NONE cterm=NONE
  hi Purple ctermfg=134 ctermbg=NONE cterm=NONE
  hi Grey ctermfg=247 ctermbg=NONE cterm=NONE
  if get(g:, 'dark_and_light_transp_bg', 0)
    hi Normal ctermfg=242 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=242 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=242 ctermbg=231 cterm=NONE
    hi Terminal ctermfg=242 ctermbg=231 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi Conceal ctermfg=247 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=242 ctermbg=255 cterm=NONE
  hi LineNr ctermfg=247 ctermbg=255 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=230 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=255 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=224 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=255 cterm=NONE
  hi Directory ctermfg=107 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=231 ctermbg=231 cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=172 ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=68 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=134 ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=247 ctermbg=255 cterm=NONE
  hi Folded ctermfg=247 ctermbg=255 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=254 cterm=underline
  hi Search ctermfg=NONE ctermbg=254 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=247 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=242 ctermbg=254 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=68 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=254 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=247 cterm=NONE
  hi Question ctermfg=107 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=172 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=68 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=134 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=242 ctermbg=254 cterm=NONE
  hi StatusLineNC ctermfg=247 ctermbg=255 cterm=NONE
  hi TabLine ctermfg=242 ctermbg=254 cterm=NONE
  hi TabLineFill ctermfg=247 ctermbg=255 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=134 cterm=NONE
  hi VertSplit ctermfg=254 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu ctermfg=231 ctermbg=107 cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=242 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=247 cterm=NONE
  hi ToolbarButton ctermfg=242 ctermbg=231 cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi PreProc ctermfg=167 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=167 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=167 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi Define ctermfg=167 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=167 ctermbg=NONE cterm=NONE
  hi Special ctermfg=172 ctermbg=NONE cterm=NONE
  hi Type ctermfg=172 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=172 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=107 ctermbg=NONE cterm=NONE
  hi String ctermfg=107 ctermbg=NONE cterm=NONE
  hi Character ctermfg=107 ctermbg=NONE cterm=NONE
  hi Number ctermfg=107 ctermbg=NONE cterm=NONE
  hi Float ctermfg=107 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=72 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=72 ctermbg=NONE cterm=NONE
  hi Function ctermfg=68 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=68 ctermbg=NONE cterm=NONE
  hi Title ctermfg=68 ctermbg=NONE cterm=bold
  hi Label ctermfg=68 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=68 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=134 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=134 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=134 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=134 ctermbg=NONE cterm=italic
  hi StorageClass ctermfg=134 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=134 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=134 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=242 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=247 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=247 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=247 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  if !s:italics
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'dark_and_light_transp_bg', 0)
      hi Normal ctermfg=White ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=White ctermbg=Black cterm=NONE
      hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
    hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=LightGrey cterm=NONE
    hi LineNr ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
    hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=LightYellow cterm=NONE
    hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
    hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
    hi ModeMsg ctermfg=Blue ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=Magenta ctermbg=NONE cterm=bold
    hi FoldColumn ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi Folded ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi IncSearch ctermfg=NONE ctermbg=LightGrey cterm=underline
    hi Search ctermfg=NONE ctermbg=LightGrey cterm=underline
    hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
    hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=White ctermbg=LightGrey cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=Blue cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=Grey cterm=NONE
    hi Question ctermfg=Green ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
    hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=White ctermbg=LightGrey cterm=NONE
    hi StatusLineNC ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi TabLine ctermfg=White ctermbg=LightGrey cterm=NONE
    hi TabLineFill ctermfg=Grey ctermbg=LightGrey cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=Magenta cterm=NONE
    hi VertSplit ctermfg=LightGrey ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
    hi WildMenu ctermfg=Black ctermbg=Green cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
    hi ToolbarLine ctermfg=NONE ctermbg=Grey cterm=NONE
    hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
    hi! link QuickFixLine Search
    hi! link lCursor Cursor
    hi! link StatusLineTerm StatusLine
    hi! link StatusLineTermNC StatusLineNC
    hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
    hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
    hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
    hi Define ctermfg=Red ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
    hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Structure ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
    hi String ctermfg=Green ctermbg=NONE cterm=NONE
    hi Character ctermfg=Green ctermbg=NONE cterm=NONE
    hi Number ctermfg=Green ctermbg=NONE cterm=NONE
    hi Float ctermfg=Green ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Title ctermfg=Blue ctermbg=NONE cterm=bold
    hi Label ctermfg=Blue ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Todo ctermfg=Magenta ctermbg=NONE cterm=italic
    hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Statement ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Tag ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
    hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
    hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
    hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi! link SpecialChar Special
    hi! link Debug Special
    hi! link Include PreProc
    if !s:italics
      hi Todo cterm=NONE
      hi Comment cterm=NONE
      hi SpecialComment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  hi Fg ctermfg=Black ctermbg=NONE cterm=NONE
  hi Red ctermfg=Red ctermbg=NONE cterm=NONE
  hi Yellow ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Green ctermfg=Green ctermbg=NONE cterm=NONE
  hi Cyan ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Blue ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Purple ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Grey ctermfg=Grey ctermbg=NONE cterm=NONE
  if get(g:, 'dark_and_light_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=White cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=bold
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=Blue ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=Magenta ctermbg=NONE cterm=bold
  hi FoldColumn ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi Search ctermfg=NONE ctermbg=LightGrey cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Blue cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Grey cterm=NONE
  hi Question ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi StatusLineNC ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Magenta cterm=NONE
  hi VertSplit ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=reverse
  hi WildMenu ctermfg=White ctermbg=Green cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=White cterm=bold
  hi! link QuickFixLine Search
  hi! link lCursor Cursor
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Red ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Red ctermbg=NONE cterm=NONE
  hi Special ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Title ctermfg=Blue ctermbg=NONE cterm=bold
  hi Label ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=italic
  hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Black ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi! link SpecialChar Special
  hi! link Debug Special
  hi! link Include PreProc
  if !s:italics
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: background    #262729           ~                 Black
" Color: foreground    #b7bec9           ~                 White
" Color: red           #e77171           ~                 Red
" Color: yellow        #ddb66c           ~                 Yellow
" Color: green         #a1bf78           ~                 Green
" Color: cyan          #73c19f           ~                 Cyan
" Color: blue          #7dbaec           ~                 Blue
" Color: purple        #d390e7           ~                 Magenta
" Color: grey          #88909f           ~                 Grey
" Color: background_alt #2d2f33          ~                 LightGrey
" Color: background_grey #3e4249         ~                 LightGrey
" Color: background_red #362023          ~                 LightRed
" Color: background_green #293323        ~                 LightGreen
" Color: background_yellow #2b261b       ~                 LightYellow
" Color: background_blue #1e232d         ~                 LightBlue
" Term colors: fg red green yellow blue purple cyan grey
" Term colors: fg red green yellow blue purple cyan grey
" Background: light
" Color: background    #fafafa           ~                 White
" Color: foreground    #656c78           ~                 Black
" Color: red           #db7070           ~                 Red
" Color: yellow        #d69822           ~                 Yellow
" Color: green         #7c9f4b           ~                 Green
" Color: cyan          #529c7d           ~                 Cyan
" Color: blue          #6587bf           ~                 Blue
" Color: purple        #b870ce           ~                 Magenta
" Color: grey          #949ba5           ~                 Grey
" Color: background_alt #eceff2          ~                 LightGrey
" Color: background_grey #dde2e7         ~                 LightGrey
" Color: background_red #f4e2e3          ~                 LightRed
" Color: background_green #e5f4de        ~                 LightGreen
" Color: background_yellow #f4edde       ~                 LightYellow
" Color: background_blue #e6edf9         ~                 LightBlue
" Term colors: fg red green yellow blue purple cyan grey
" Term colors: fg red green yellow blue purple cyan grey
" Background: any
" vim: et ts=2 sw=2
